[env]
# Python version requirement
python = "3.13.11"

[tools]
# Python environment tools
python = "3.13.11"

[tasks]
# Task to install required dependencies
install = """
pip install ipykernel sortedcontainers
"""

# Task to run notebooks
notebooks = """
jupyter notebook
"""